<?php

/**
 * PluginBbsImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginBbsImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginBbsImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginBbsImage');
    }
}