<?php

/**
 * PluginBbsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginBbsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginBbsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginBbs');
    }
}