<?php

/**
 * PluginBbsCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginBbsCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginBbsCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginBbsComment');
    }
}