<?php

/**
 * PluginBbsCommentImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginBbsCommentImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginBbsCommentImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginBbsCommentImage');
    }
}