<?php

/**
 * PluginBbs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginBbs extends BaseBbs
{
  protected $previous, $next;
  protected $countBbsComments;

  public function isEditable($memberId)
  {
    return ($this->getMemberId() === $memberId);
  }

  public function getPrevious()
  {
    if (is_null($this->previous))
    {
      $this->previous = $this->getTable()->getPreviousBbs($this);
    }

    return $this->previous;
  }

  public function getNext()
  {
    if (is_null($this->next))
    {
      $this->next = $this->getTable()->getNextBbs($this);
    }

    return $this->next;
  }

  public function countBbsComments($noCache = false)
  {
    if ($noCache || is_null($this->countBbsComments))
    {
      $this->countBbsComments = Doctrine::getTable('BbsComment')->getCount($this->id);
    }

    return $this->countBbsComments;
  }
}
